/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NewsRouteImport } from './routes/news'
import { Route as HonorRouteImport } from './routes/honor'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AcademicRouteImport } from './routes/academic'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as HonorIndexRouteImport } from './routes/honor.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AchievementsIndexRouteImport } from './routes/achievements.index'
import { Route as AcademicIndexRouteImport } from './routes/academic.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as AdminTimelineRouteImport } from './routes/admin.timeline'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminModuleRouteImport } from './routes/admin.$module'
import { Route as AchievementsSlugRouteImport } from './routes/achievements.$slug'
import { Route as AcademicStudentGuidelinesRouteImport } from './routes/academic.student-guidelines'
import { Route as AcademicPoliciesRouteImport } from './routes/academic.policies'
import { Route as AcademicParentGuidelinesRouteImport } from './routes/academic.parent-guidelines'
import { Route as AcademicFaqRouteImport } from './routes/academic.faq'
import { Route as AcademicCalendarRouteImport } from './routes/academic.calendar'
import { Route as AcademicBehaviourRouteImport } from './routes/academic.behaviour'
import { Route as AcademicAttendanceBehaviourRouteImport } from './routes/academic.attendance-behaviour'
import { Route as AcademicAttendanceRouteImport } from './routes/academic.attendance'
import { Route as HonorGradesLevelRouteImport } from './routes/honor.grades.$level'
import { Route as AcademicGradesLevelRouteImport } from './routes/academic.grades.$level'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorRoute = HonorRouteImport.update({
  id: '/honor',
  path: '/honor',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRoute = AcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const HonorIndexRoute = HonorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HonorRoute,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AchievementsIndexRoute = AchievementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AchievementsRoute,
} as any)
const AcademicIndexRoute = AcademicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademicRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalleryRoute,
} as any)
const AdminTimelineRoute = AdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModuleRoute = AdminModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AdminRoute,
} as any)
const AchievementsSlugRoute = AchievementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AchievementsRoute,
} as any)
const AcademicStudentGuidelinesRoute =
  AcademicStudentGuidelinesRouteImport.update({
    id: '/student-guidelines',
    path: '/student-guidelines',
    getParentRoute: () => AcademicRoute,
  } as any)
const AcademicPoliciesRoute = AcademicPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AcademicRoute,
} as any)
const AcademicParentGuidelinesRoute =
  AcademicParentGuidelinesRouteImport.update({
    id: '/parent-guidelines',
    path: '/parent-guidelines',
    getParentRoute: () => AcademicRoute,
  } as any)
const AcademicFaqRoute = AcademicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AcademicRoute,
} as any)
const AcademicCalendarRoute = AcademicCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AcademicRoute,
} as any)
const AcademicBehaviourRoute = AcademicBehaviourRouteImport.update({
  id: '/behaviour',
  path: '/behaviour',
  getParentRoute: () => AcademicRoute,
} as any)
const AcademicAttendanceBehaviourRoute =
  AcademicAttendanceBehaviourRouteImport.update({
    id: '/attendance-behaviour',
    path: '/attendance-behaviour',
    getParentRoute: () => AcademicRoute,
  } as any)
const AcademicAttendanceRoute = AcademicAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AcademicRoute,
} as any)
const HonorGradesLevelRoute = HonorGradesLevelRouteImport.update({
  id: '/grades/$level',
  path: '/grades/$level',
  getParentRoute: () => HonorRoute,
} as any)
const AcademicGradesLevelRoute = AcademicGradesLevelRouteImport.update({
  id: '/grades/$level',
  path: '/grades/$level',
  getParentRoute: () => AcademicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRouteWithChildren
  '/achievements': typeof AchievementsRouteWithChildren
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/honor': typeof HonorRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/attendance-behaviour': typeof AcademicAttendanceBehaviourRoute
  '/academic/behaviour': typeof AcademicBehaviourRoute
  '/academic/calendar': typeof AcademicCalendarRoute
  '/academic/faq': typeof AcademicFaqRoute
  '/academic/parent-guidelines': typeof AcademicParentGuidelinesRoute
  '/academic/policies': typeof AcademicPoliciesRoute
  '/academic/student-guidelines': typeof AcademicStudentGuidelinesRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/admin/$module': typeof AdminModuleRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academic/': typeof AcademicIndexRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/honor/': typeof HonorIndexRoute
  '/news/': typeof NewsIndexRoute
  '/academic/grades/$level': typeof AcademicGradesLevelRoute
  '/honor/grades/$level': typeof HonorGradesLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/attendance-behaviour': typeof AcademicAttendanceBehaviourRoute
  '/academic/behaviour': typeof AcademicBehaviourRoute
  '/academic/calendar': typeof AcademicCalendarRoute
  '/academic/faq': typeof AcademicFaqRoute
  '/academic/parent-guidelines': typeof AcademicParentGuidelinesRoute
  '/academic/policies': typeof AcademicPoliciesRoute
  '/academic/student-guidelines': typeof AcademicStudentGuidelinesRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/admin/$module': typeof AdminModuleRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academic': typeof AcademicIndexRoute
  '/achievements': typeof AchievementsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/honor': typeof HonorIndexRoute
  '/news': typeof NewsIndexRoute
  '/academic/grades/$level': typeof AcademicGradesLevelRoute
  '/honor/grades/$level': typeof HonorGradesLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRouteWithChildren
  '/achievements': typeof AchievementsRouteWithChildren
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/honor': typeof HonorRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/attendance-behaviour': typeof AcademicAttendanceBehaviourRoute
  '/academic/behaviour': typeof AcademicBehaviourRoute
  '/academic/calendar': typeof AcademicCalendarRoute
  '/academic/faq': typeof AcademicFaqRoute
  '/academic/parent-guidelines': typeof AcademicParentGuidelinesRoute
  '/academic/policies': typeof AcademicPoliciesRoute
  '/academic/student-guidelines': typeof AcademicStudentGuidelinesRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/admin/$module': typeof AdminModuleRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academic/': typeof AcademicIndexRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/honor/': typeof HonorIndexRoute
  '/news/': typeof NewsIndexRoute
  '/academic/grades/$level': typeof AcademicGradesLevelRoute
  '/honor/grades/$level': typeof HonorGradesLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic'
    | '/achievements'
    | '/activities'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/honor'
    | '/news'
    | '/search'
    | '/sitemap.xml'
    | '/academic/attendance'
    | '/academic/attendance-behaviour'
    | '/academic/behaviour'
    | '/academic/calendar'
    | '/academic/faq'
    | '/academic/parent-guidelines'
    | '/academic/policies'
    | '/academic/student-guidelines'
    | '/achievements/$slug'
    | '/admin/$module'
    | '/admin/contact'
    | '/admin/documents'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/timeline'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/academic/'
    | '/achievements/'
    | '/admin/'
    | '/gallery/'
    | '/honor/'
    | '/news/'
    | '/academic/grades/$level'
    | '/honor/grades/$level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/contact'
    | '/search'
    | '/sitemap.xml'
    | '/academic/attendance'
    | '/academic/attendance-behaviour'
    | '/academic/behaviour'
    | '/academic/calendar'
    | '/academic/faq'
    | '/academic/parent-guidelines'
    | '/academic/policies'
    | '/academic/student-guidelines'
    | '/achievements/$slug'
    | '/admin/$module'
    | '/admin/contact'
    | '/admin/documents'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/timeline'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/academic'
    | '/achievements'
    | '/admin'
    | '/gallery'
    | '/honor'
    | '/news'
    | '/academic/grades/$level'
    | '/honor/grades/$level'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic'
    | '/achievements'
    | '/activities'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/honor'
    | '/news'
    | '/search'
    | '/sitemap.xml'
    | '/academic/attendance'
    | '/academic/attendance-behaviour'
    | '/academic/behaviour'
    | '/academic/calendar'
    | '/academic/faq'
    | '/academic/parent-guidelines'
    | '/academic/policies'
    | '/academic/student-guidelines'
    | '/achievements/$slug'
    | '/admin/$module'
    | '/admin/contact'
    | '/admin/documents'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/timeline'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/academic/'
    | '/achievements/'
    | '/admin/'
    | '/gallery/'
    | '/honor/'
    | '/news/'
    | '/academic/grades/$level'
    | '/honor/grades/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicRoute: typeof AcademicRouteWithChildren
  AchievementsRoute: typeof AchievementsRouteWithChildren
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  HonorRoute: typeof HonorRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honor': {
      id: '/honor'
      path: '/honor'
      fullPath: '/honor'
      preLoaderRoute: typeof HonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/honor/': {
      id: '/honor/'
      path: '/'
      fullPath: '/honor/'
      preLoaderRoute: typeof HonorIndexRouteImport
      parentRoute: typeof HonorRoute
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/achievements/': {
      id: '/achievements/'
      path: '/'
      fullPath: '/achievements/'
      preLoaderRoute: typeof AchievementsIndexRouteImport
      parentRoute: typeof AchievementsRoute
    }
    '/academic/': {
      id: '/academic/'
      path: '/'
      fullPath: '/academic/'
      preLoaderRoute: typeof AcademicIndexRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/admin/timeline': {
      id: '/admin/timeline'
      path: '/timeline'
      fullPath: '/admin/timeline'
      preLoaderRoute: typeof AdminTimelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$module': {
      id: '/admin/$module'
      path: '/$module'
      fullPath: '/admin/$module'
      preLoaderRoute: typeof AdminModuleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/achievements/$slug': {
      id: '/achievements/$slug'
      path: '/$slug'
      fullPath: '/achievements/$slug'
      preLoaderRoute: typeof AchievementsSlugRouteImport
      parentRoute: typeof AchievementsRoute
    }
    '/academic/student-guidelines': {
      id: '/academic/student-guidelines'
      path: '/student-guidelines'
      fullPath: '/academic/student-guidelines'
      preLoaderRoute: typeof AcademicStudentGuidelinesRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/policies': {
      id: '/academic/policies'
      path: '/policies'
      fullPath: '/academic/policies'
      preLoaderRoute: typeof AcademicPoliciesRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/parent-guidelines': {
      id: '/academic/parent-guidelines'
      path: '/parent-guidelines'
      fullPath: '/academic/parent-guidelines'
      preLoaderRoute: typeof AcademicParentGuidelinesRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/faq': {
      id: '/academic/faq'
      path: '/faq'
      fullPath: '/academic/faq'
      preLoaderRoute: typeof AcademicFaqRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/calendar': {
      id: '/academic/calendar'
      path: '/calendar'
      fullPath: '/academic/calendar'
      preLoaderRoute: typeof AcademicCalendarRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/behaviour': {
      id: '/academic/behaviour'
      path: '/behaviour'
      fullPath: '/academic/behaviour'
      preLoaderRoute: typeof AcademicBehaviourRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/attendance-behaviour': {
      id: '/academic/attendance-behaviour'
      path: '/attendance-behaviour'
      fullPath: '/academic/attendance-behaviour'
      preLoaderRoute: typeof AcademicAttendanceBehaviourRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/attendance': {
      id: '/academic/attendance'
      path: '/attendance'
      fullPath: '/academic/attendance'
      preLoaderRoute: typeof AcademicAttendanceRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/honor/grades/$level': {
      id: '/honor/grades/$level'
      path: '/grades/$level'
      fullPath: '/honor/grades/$level'
      preLoaderRoute: typeof HonorGradesLevelRouteImport
      parentRoute: typeof HonorRoute
    }
    '/academic/grades/$level': {
      id: '/academic/grades/$level'
      path: '/grades/$level'
      fullPath: '/academic/grades/$level'
      preLoaderRoute: typeof AcademicGradesLevelRouteImport
      parentRoute: typeof AcademicRoute
    }
  }
}

interface AcademicRouteChildren {
  AcademicAttendanceRoute: typeof AcademicAttendanceRoute
  AcademicAttendanceBehaviourRoute: typeof AcademicAttendanceBehaviourRoute
  AcademicBehaviourRoute: typeof AcademicBehaviourRoute
  AcademicCalendarRoute: typeof AcademicCalendarRoute
  AcademicFaqRoute: typeof AcademicFaqRoute
  AcademicParentGuidelinesRoute: typeof AcademicParentGuidelinesRoute
  AcademicPoliciesRoute: typeof AcademicPoliciesRoute
  AcademicStudentGuidelinesRoute: typeof AcademicStudentGuidelinesRoute
  AcademicIndexRoute: typeof AcademicIndexRoute
  AcademicGradesLevelRoute: typeof AcademicGradesLevelRoute
}

const AcademicRouteChildren: AcademicRouteChildren = {
  AcademicAttendanceRoute: AcademicAttendanceRoute,
  AcademicAttendanceBehaviourRoute: AcademicAttendanceBehaviourRoute,
  AcademicBehaviourRoute: AcademicBehaviourRoute,
  AcademicCalendarRoute: AcademicCalendarRoute,
  AcademicFaqRoute: AcademicFaqRoute,
  AcademicParentGuidelinesRoute: AcademicParentGuidelinesRoute,
  AcademicPoliciesRoute: AcademicPoliciesRoute,
  AcademicStudentGuidelinesRoute: AcademicStudentGuidelinesRoute,
  AcademicIndexRoute: AcademicIndexRoute,
  AcademicGradesLevelRoute: AcademicGradesLevelRoute,
}

const AcademicRouteWithChildren = AcademicRoute._addFileChildren(
  AcademicRouteChildren,
)

interface AchievementsRouteChildren {
  AchievementsSlugRoute: typeof AchievementsSlugRoute
  AchievementsIndexRoute: typeof AchievementsIndexRoute
}

const AchievementsRouteChildren: AchievementsRouteChildren = {
  AchievementsSlugRoute: AchievementsSlugRoute,
  AchievementsIndexRoute: AchievementsIndexRoute,
}

const AchievementsRouteWithChildren = AchievementsRoute._addFileChildren(
  AchievementsRouteChildren,
)

interface AdminRouteChildren {
  AdminModuleRoute: typeof AdminModuleRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminTimelineRoute: typeof AdminTimelineRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminModuleRoute: AdminModuleRoute,
  AdminContactRoute: AdminContactRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminTimelineRoute: AdminTimelineRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GalleryRouteChildren {
  GallerySlugRoute: typeof GallerySlugRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GallerySlugRoute: GallerySlugRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface HonorRouteChildren {
  HonorIndexRoute: typeof HonorIndexRoute
  HonorGradesLevelRoute: typeof HonorGradesLevelRoute
}

const HonorRouteChildren: HonorRouteChildren = {
  HonorIndexRoute: HonorIndexRoute,
  HonorGradesLevelRoute: HonorGradesLevelRoute,
}

const HonorRouteWithChildren = HonorRoute._addFileChildren(HonorRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicRoute: AcademicRouteWithChildren,
  AchievementsRoute: AchievementsRouteWithChildren,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRouteWithChildren,
  HonorRoute: HonorRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
